name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for ARM
        run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker buildx build --platform linux/arm/v7 -t ghcr.io/gbx-archive/website:latest -f docker/Dockerfile --load .
            docker push ghcr.io/gbx-archive/website:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519

      - name: deploy
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker pull ghcr.io/gbx-archive/website:latest'
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker stop gbx-archive-website || true'
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker rm gbx-archive-website || true'
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 'docker run -d --name gbx-archive-website -p 3000:3000 --env REACT_APP_API_URL=${{ secrets.API_URL }} ghcr.io/gbx-archive/website:latest'

      - name: Clean up SSH key
        run: |
            rm ~/.ssh/id_ed25519
            rm ~/.ssh/known_hosts
